#+title: Mangawae Org Mode
#+DESCRIPTION: An org document to organize the Mangawae project!
#+AUTHOR: Jah's Dalmation

* Key

'' = Description
- = Implementation
! = Function/File utilized
!! = Function/File called

* Mangawae
DEADLINE: <2022-07-17 Sun 00:00> SCHEDULED: <2022-07-14 Thu 00:00>

'Mangawae is a simple python based program, designed to search, download and
    read manga! The Mangawae program will always begin with a warm welcome
    message to great new users and if needed, provide help. The Mangawae
    program itself will only be run once, however the menu's within are
    designed to be looped'

- Program start
- Welcome message "Hello and Welcome to Mangawae!"
- Main Menu
! Mangawae.py
!! Main_Menu() / Main_Menu.py

** TODO Main Menu [3/4]
*** [ ] Local [0/2]
SCHEDULED: <2022-07-15 Fri 16:00> DEADLINE: <2022-07-17 Sun 00:00>
**** [ ] Browse
***** [ ] Read

**** [ ] Back

*** [X] External [0/0]
SCHEDULED: <2022-07-14 Thu 16:00> DEADLINE: <2022-07-15 Fri 00:00>
**** [X] Newest [0/0]
'Browse a selection of (default: 10) manga, chosen based on Newest'

***** [X] Select [0/0]
Choose an avaliable manga and get details.

****** [X] Download [0/0]
******* [X] EP
******* [X] Final EP
****** [X] Back

***** [X] Back

**** [X] Hottest [0/0]
Browse a selection of (default: 5) manga, chosen based on Hottest!

***** [X] Select [0/0]
****** [X] Download [0/0]
******* [X] EP
******* [X] Final EP
****** [X] Back

***** [X] Back

**** [X] Latest [0/0]
Browse a selection of (default: 5) manga, chosen based on Latest!
***** [X] Select [0/0]
****** [X] Download [0/0]
******* [X] EP
******* [X] Final EP
****** [X] Back
***** [X] Back

**** [X] Search [0/0]
Scrape the manganato website for results matching the given string.
***** [X] Select [0/0]
****** [X] Download [0/0]
******* [X] EP
******* [X] Final EP
****** [X] Back
***** [X] Back
*** [X] Help [0/0]
**** [X] Dedicated and Interactive Help menu!
DEADLINE: <2022-07-14 Thu 02:30> SCHEDULED: <2022-07-14 Thu 00:00>
*** [X] Quit
